/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SORT_H_RPCGEN
#define _SORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct Array {
	char val[40];
};
typedef struct Array Array;


#define SORT_PROG 0x31415926
#define Bubble_Sort_algo 1

#if defined(__STDC__) || defined(__cplusplus)
#define Bsort 1
extern  Array * bsort_1(Array *, CLIENT *);
extern  Array * bsort_1_svc(Array *, struct svc_req *);
extern int sort_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Bsort 1
extern  Array * bsort_1();
extern  Array * bsort_1_svc();
extern int sort_prog_1_freeresult ();
#endif /* K&R C */
#define Merge_Sort_algo 2

#if defined(__STDC__) || defined(__cplusplus)
#define Msort 1
extern  Array * msort_2(Array *, CLIENT *);
extern  Array * msort_2_svc(Array *, struct svc_req *);
extern int sort_prog_2_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define Msort 1
extern  Array * msort_2();
extern  Array * msort_2_svc();
extern int sort_prog_2_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Array (XDR *, Array*);
extern  bool_t xdr_Array (XDR *, Array*);

#else /* K&R C */
extern bool_t xdr_Array ();
extern bool_t xdr_Array ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SORT_H_RPCGEN */
